name: Event Name Detector

on:   
  push:                
  pull_request:        

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show event name
        run: echo "I've been triggered by ${{ github.event_name }} event"
